AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  identity-store-lambda

  SAM Template for identity-store-API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  IdentityStoreApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !GetAtt Authorizer.Arn

  Groups:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./groups
      Description: ""
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - identitystore:*
              Resource: "*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-west-1:416469482962:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-west-1:416469482962:log-group:/aws/lambda/CreateGroup:*
      SnapStart:
        ApplyOn: None
      Events:
        Api3:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /groups
            Method: GET
        Api4:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /groups
            Method: POST
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  Group:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./group
      Description: ""
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - identitystore:*
              Resource: "*"
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /groups/{groupId}
            Method: GET
        Api2:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /groups/{groupId}
            Method: DELETE
        Api3:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /groups/{groupId}
            Method: PATCH
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  MembershipGroups:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./membership_groups
      Description: ""
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - identitystore:*
              Resource: "*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-west-1:416469482962:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-west-1:416469482962:log-group:/aws/lambda/CreateGroup:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /memberships/groups/{groupId}
            Method: GET
        Api2:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /memberships/groups/{groupId}
            Method: DELETE
        Api3:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /memberships/groups/{groupId}
            Method: POST
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  Memberships:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./memberships
      Description: ""
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - identitystore:*
              Resource: "*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-west-1:416469482962:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-west-1:416469482962:log-group:/aws/lambda/CreateGroup:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /memberships/{membershipId}
            Method: GET
        Api2:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /memberships/{membershipId}
            Method: DELETE
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  User:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./user
      Description: ""
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - identitystore:*
              Resource: "*"
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /users/{userId}
            Method: GET
        Api2:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /users/{userId}
            Method: DELETE
        Api3:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /users/{userId}
            Method: PATCH
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  Users:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./users
      Description: ""
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - identitystore:*
              Resource: "*"
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /users
            Method: GET
        Api2:
          Type: Api
          Properties:
            RestApiId: !Ref IdentityStoreApi
            Path: /users
            Method: POST
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./authorizer
      Description: ""
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-west-1:416469482962:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-west-1:416469482962:log-group:/aws/lambda/Authorizer:*
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
